<template>
  <div class="toolbar">
    <el-button-group>
      <el-button @click="undo" :disabled="!canUndo">撤销</el-button>
      <el-button @click="clearAll">清屏</el-button>
    </el-button-group>

    <el-divider />

    <el-button-group>
      <el-button :type="showGrid ? 'primary' : 'default'" @click="toggleGrid">
        {{ showGrid ? '隐藏网格' : '显示网格' }}
      </el-button>
      <el-button :type="showAxes ? 'primary' : 'default'" @click="toggleAxes">
        {{ showAxes ? '隐藏坐标轴' : '显示坐标轴' }}
      </el-button>
    </el-button-group>

    <el-divider />

    <el-dropdown @command="handleExecuteCommand" trigger="click">
      <el-button type="primary">
        Execute <el-icon class="el-icon--right"><arrow-down /></el-icon>
      </el-button>
      <template #dropdown>
        <el-dropdown-menu>
          <el-dropdown-item command="qmorph">Execute Q-Morph</el-dropdown-item>
        </el-dropdown-menu>
      </template>
    </el-dropdown>

    <el-divider />

    <div class="zoom-control">
      <el-slider
        v-model="zoom"
        :min="10"
        :max="400"
        :step="10"
        vertical
        height="150px"
      />
    </div>

    <el-divider />

    <el-button-group>
      <el-button @click="exportToLatex">导出LaTeX</el-button>
      <el-button @click="importFile">导入文件</el-button>
    </el-button-group>
  </div>

  <!-- QMorph参数对话框 -->
  <QMorphParameters ref="qmorphDialog" />
</template>

<script setup lang="ts">
import { ref, computed } from 'vue'
import { ArrowDown } from '@element-plus/icons-vue'
import { useMeshStore } from '@/store/mesh'
import { ElMessage } from 'element-plus'
import { saveAs } from 'file-saver'
import { parseMeshFile, parseDtaFile } from '@/utils/fileParser'
import type { Node, Edge } from '@/types/mesh'
import QMorphParameters from '../dialog/QMorphParameters.vue'

const meshStore = useMeshStore()
const qmorphDialog = ref()

// 撤销/重做
const canUndo = computed(() => meshStore.currentHistoryIndex > 0)
const undo = () => meshStore.undo()
const clearAll = () => meshStore.clearAll()

// 显示控制
const showGrid = computed({
  get: () => meshStore.showGrid,
  set: (value) => meshStore.setShowGrid(value)
})

const showAxes = computed({
  get: () => meshStore.showAxes,
  set: (value) => meshStore.setShowAxes(value)
})

// 缩放控制
const zoom = computed({
  get: () => meshStore.zoom,
  set: (value) => meshStore.setZoom(value)
})

// 切换网格显示
const toggleGrid = () => {
  showGrid.value = !showGrid.value
}

// 切换坐标轴显示
const toggleAxes = () => {
  showAxes.value = !showAxes.value
}

// 处理执行命令
const handleExecuteCommand = (command: string) => {
  if (command === 'qmorph') {
    qmorphDialog.value.show()
  }
}

// 文件操作
const exportToLatex = () => {
  // 实现导出到LaTeX的功能
  const content = generateLatexContent()
  const blob = new Blob([content], { type: 'text/plain;charset=utf-8' })
  saveAs(blob, 'mesh.tex')
}

const importFile = () => {
  const input = document.createElement('input')
  input.type = 'file'
  input.accept = '.mesh,.dta'
  input.onchange = async (e: Event) => {
    const file = (e.target as HTMLInputElement).files?.[0]
    if (file) {
      try {
        const content = await file.text()
        let meshData: { nodes: Node[]; edges: Edge[] }
        
        if (file.name.endsWith('.mesh')) {
          meshData = parseMeshFile(content)
        } else if (file.name.endsWith('.dta')) {
          meshData = parseDtaFile(content)
        } else {
          throw new Error('不支持的文件格式')
        }

        // 更新store中的数据
        meshStore.$patch({
          nodes: meshData.nodes,
          edges: meshData.edges
        })
        meshStore.saveToHistory() // 保存到历史记录并触发视图更新
        
        ElMessage.success('文件导入成功')
      } catch (error) {
        console.error('导入错误:', error)
        ElMessage.error('文件导入失败: ' + (error as Error).message)
      }
    }
  }
  input.click()
}

const generateLatexContent = () => {
  // 生成LaTeX格式的内容
  return `% Generated by Mesh Editor
\\documentclass{article}
\\usepackage{tikz}
\\begin{document}
\\begin{tikzpicture}
  % Nodes
  ${meshStore.nodes.map(node => `\\node[circle,draw] (${node.id}) at (${node.x},${node.y}) {};`).join('\n  ')}
  
  % Edges
  ${meshStore.edges.map(edge => `\\draw (${edge.startNodeId}) -- (${edge.endNodeId});`).join('\n  ')}
\\end{tikzpicture}
\\end{document}`
}
</script>

<style scoped>
.toolbar {
  padding: 10px;
  background-color: #1e1e1e;
  border-right: 1px solid #333;
  height: 100%;
  display: flex;
  flex-direction: column;
  gap: 10px;
}

.el-button-group {
  display: flex;
  flex-direction: column;
  gap: 5px;
}

.el-divider {
  margin: 10px 0;
  background-color: #333;
}

.zoom-control {
  display: flex;
  justify-content: center;
  padding: 10px 0;
}

:deep(.el-slider) {
  margin: 0;
}

:deep(.el-slider__runway) {
  background-color: #4a4a4a;
}

:deep(.el-slider__bar) {
  background-color: #409eff;
}

:deep(.el-slider__button) {
  border-color: #409eff;
}
</style> 